export const timesheetData = [
  {
    id: 1,
    employeeId: 1,
    employeeName: "Emily Johnson",
    week: "2026-09-01",
    title: "Dashboard Development",
    task: "Worked on the employee dashboard UI and implemented responsive components.",
    startTime: "09:00",
    endTime: "17:00",
    totalHours: 8,
    status: "Pending",
  },
  {
    id: 2,
    employeeId: 2,
    employeeName: "Michael Williams",
    week: "2026-09-01",
    title: "Authentication Module",
    task: "Fixed login validation and implemented protected route handling.",
    startTime: "09:30",
    endTime: "17:00",
    totalHours: 7.5,
    status: "Approved",
  },
  {
    id: 3,
    employeeId: 3,
    employeeName: "Sophia Brown",
    week: "2026-09-02",
    title: "Employee Management",
    task: "Developed employee listing, search, filtering and sorting functionality.",
    startTime: "09:00",
    endTime: "17:00",
    totalHours: 8,
    status: "Pending",
  },
  {
    id: 4,
    employeeId: 4,
    employeeName: "James Davis",
    week: "2026-09-02",
    title: "API Integration",
    task: "Integrated employee APIs and handled loading and error states.",
    startTime: "10:00",
    endTime: "16:30",
    totalHours: 6.5,
    status: "Rejected",
  },
  {
    id: 5,
    employeeId: 5,
    employeeName: "Emma Miller",
    week: "2026-09-03",
    title: "Testing",
    task: "Performed application testing and fixed issues found during testing.",
    startTime: "09:00",
    endTime: "17:00",
    totalHours: 8,
    status: "Pending",
  },
];

export default timesheetData;
